### ISSUE TITLE
Child HtmlWebpackCompiler Broken build error when run storybook in tutorial

### ISSUE THREAD

**Issue by simongcc** [chromaui/intro-storybook-vue-template#3]
Hello! Really excited after seeing what Storybook does. I am a vue developer.
I encountered the captioned error when following the tutorial for vue https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/

The `test:unit` and `yarn serve` runs well but `yarn storybook`.

System Environment
MacOS 10.14.6
@vue/cli 4.5.12
npx/npm 6.14.6
yarn 1.22.10

End up solutions in my case is
yarn add vue-loader@next --dev because the package.json, the vue is 3.0.0, after running it turns to 3.0.11, seems version of vue cause the problem.

Hopefully it could help anyone in trouble.

Error for reference
```
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.41 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/builder-webpack4/node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.96 KiB {HtmlWebpackPlugin_0} [built]
ModuleError: Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at Object.emitError (/Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:173:6)
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:21)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
    at LOADER_EXECUTION (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:31)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
ModuleError: Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at Object.emitError (/Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:173:6)
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:21)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
    at LOADER_EXECUTION (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:31)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
ModuleError: Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at Object.emitError (/Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:173:6)
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:21)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
    at LOADER_EXECUTION (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at loadTemplateCompiler (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:24:31)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:69:35)
ModuleBuildError: Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Volumes/Ram2/taskbox/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:67:22)
    at /Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:316:20
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
ModuleBuildError: Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Volumes/Ram2/taskbox/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:67:22)
    at /Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:316:20
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
ModuleBuildError: Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Volumes/Ram2/taskbox/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Volumes/Ram2/taskbox/node_modules/vue-loader/lib/index.js:67:22)
    at /Volumes/Ram2/taskbox/node_modules/webpack/lib/NormalModule.js:316:20
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Volumes/Ram2/taskbox/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Ram2/taskbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Ram2/taskbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by jonniebigodes** [comment]
@simongcc thanks for bringing this to our attention. I'm going to close this issue as with the release of 6.3 this is no longer present. It seems that something broke during the release phase of 6.2 and introduced an issue with Storybook and Vue 3. 

Stay safe
